# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainForm', '0002_auto_20170323_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigentry',
            name='week_of_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pigentry',
            name='entry_date',
            field=models.DateTimeField(),
        ),
    ]
