# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainForm', '0003_auto_20170323_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pigentry',
            old_name='number_pigs',
            new_name='number_of_pigs',
        ),
        migrations.RenameField(
            model_name='pigentry',
            old_name='room_num',
            new_name='room_number',
        ),
    ]
