# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainForm', '0004_auto_20170326_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pigentry',
            name='room_number',
        ),
        migrations.AddField(
            model_name='pigentry',
            name='flow',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainForm.Flow'),
            preserve_default=False,
        ),
    ]
