# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainForm', '0005_auto_20170424_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='abbreviation',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
