# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainForm', '0006_auto_20170424_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pigentry',
            name='flow',
        ),
    ]
