# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainForm', '0008_auto_20170424_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pigentry',
            name='flow',
        ),
    ]
