# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainForm', '0010_delete_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(default='aaa', max_length=5)),
            ],
        ),
    ]
