# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainForm', '0013_auto_20170429_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pigentry',
            name='week_of_year',
        ),
    ]
